# NOTE: hot reloading is still not really working here

apiVersion: skaffold/v4beta11
kind: Config

build:
  artifacts:
  - image: wingcloudbot/kblocks-backend
    docker:
      buildArgs: 
        ENV: prod
    sync:
      infer:
        - apps/server/src/**/*.ts
        - packages/shared/src/**/*.ts

deploy:
  helm:
    releases:
      - name: kblocks-backend
        chartPath: ./deploy
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED}}"
