{{- if .Values.source }}
{{- if .Values.source.fromImage }}
{{- if .Values.source.fromImage.image }}
apiVersion: acme.com/v1
kind: NetworkedWorkload
metadata:
  name: {{ .Release.Name }}-background-worker
  labels:
    foo: background
    hello: worker
image: {{ .Values.source.fromImage.image }}
cpu:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
memory:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
scaling:  
  {{- if and .Values.scaling .Values.scaling.autoscaling }}
  autoscaling:
    minReplicas: {{ default 2 .Values.scaling.autoscaling.minReplicas }}
    maxReplicas: {{ default 5 .Values.scaling.autoscaling.maxReplicas }}
    targetCpuUtilization: {{ default 70 .Values.scaling.autoscaling.targetCpuUtilization }}
    targetMemoryUtilization: {{ default 70 .Values.scaling.autoscaling.targetMemoryUtilization }}
  {{- else }}
  replicas: {{ if and .Values.scaling (hasKey .Values.scaling "replicas") }}{{ .Values.scaling.replicas }}{{ else }}2{{ end }}
  {{- end }}
region: {{ .Values.region }}
{{- if .Values.ingress }}
ingress:
  path: {{ .Values.ingress.path }}
  host: {{ .Values.ingress.host }}
  rewrite: {{ .Values.ingress.rewrite }}
  {{- if .Values.ingress.tls }}
  tls:
    secret: {{ .Values.ingress.tls.secret }}
    hosts: 
      {{- toYaml .Values.ingress.tls.hosts | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}