apiVersion: acme.com/v1
kind: Workload
metadata:
  name: {{ .Release.Name }}-background-worker
  labels:
    foo: background
    hello: worker
image: {{ .Values.source.fromImage.image }}
replicas: 2
env:
  ECHO_TEXT:
    value: Hello background worker