{{- if .Values.source }}
{{- if .Values.source.fromImage }}
{{- if .Values.source.fromImage.image }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: {{ .Values.source.fromImage.image }}
            command:
              {{- range .Values.command }}
            - {{ . }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}
{{- end }}
{{- end }}