/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CatalogImport } from './routes/catalog'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects.index'
import { Route as ProjectsProjectImport } from './routes/projects.$project'
import { Route as ProjectProjectImport } from './routes/project.$project'
import { Route as ResourcesGroupVersionPluralSystemNamespaceNameImport } from './routes/resources.$group.$version.$plural.$system.$namespace.$name'

// Create/Update Routes

const CatalogRoute = CatalogImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectRoute = ProjectsProjectImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRoute,
} as any)

const ProjectProjectRoute = ProjectProjectImport.update({
  id: '/project/$project',
  path: '/project/$project',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesGroupVersionPluralSystemNamespaceNameRoute =
  ResourcesGroupVersionPluralSystemNamespaceNameImport.update({
    id: '/resources/$group/$version/$plural/$system/$namespace/$name',
    path: '/resources/$group/$version/$plural/$system/$namespace/$name',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogImport
      parentRoute: typeof rootRoute
    }
    '/project/$project': {
      id: '/project/$project'
      path: '/project/$project'
      fullPath: '/project/$project'
      preLoaderRoute: typeof ProjectProjectImport
      parentRoute: typeof rootRoute
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$group/$version/$plural/$system/$namespace/$name': {
      id: '/resources/$group/$version/$plural/$system/$namespace/$name'
      path: '/resources/$group/$version/$plural/$system/$namespace/$name'
      fullPath: '/resources/$group/$version/$plural/$system/$namespace/$name'
      preLoaderRoute: typeof ResourcesGroupVersionPluralSystemNamespaceNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/project/$project': typeof ProjectProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/projects': typeof ProjectsIndexRoute
  '/resources/$group/$version/$plural/$system/$namespace/$name': typeof ResourcesGroupVersionPluralSystemNamespaceNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/project/$project': typeof ProjectProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/projects': typeof ProjectsIndexRoute
  '/resources/$group/$version/$plural/$system/$namespace/$name': typeof ResourcesGroupVersionPluralSystemNamespaceNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/project/$project': typeof ProjectProjectRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/projects/': typeof ProjectsIndexRoute
  '/resources/$group/$version/$plural/$system/$namespace/$name': typeof ResourcesGroupVersionPluralSystemNamespaceNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/project/$project'
    | '/projects/$project'
    | '/projects'
    | '/resources/$group/$version/$plural/$system/$namespace/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/project/$project'
    | '/projects/$project'
    | '/projects'
    | '/resources/$group/$version/$plural/$system/$namespace/$name'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/project/$project'
    | '/projects/$project'
    | '/projects/'
    | '/resources/$group/$version/$plural/$system/$namespace/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  ProjectProjectRoute: typeof ProjectProjectRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ResourcesGroupVersionPluralSystemNamespaceNameRoute: typeof ResourcesGroupVersionPluralSystemNamespaceNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  ProjectProjectRoute: ProjectProjectRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ResourcesGroupVersionPluralSystemNamespaceNameRoute:
    ResourcesGroupVersionPluralSystemNamespaceNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/catalog",
        "/project/$project",
        "/projects/$project",
        "/projects/",
        "/resources/$group/$version/$plural/$system/$namespace/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/catalog": {
      "filePath": "catalog.tsx"
    },
    "/project/$project": {
      "filePath": "project.$project.tsx"
    },
    "/projects/$project": {
      "filePath": "projects.$project.tsx"
    },
    "/projects/": {
      "filePath": "projects.index.tsx"
    },
    "/resources/$group/$version/$plural/$system/$namespace/$name": {
      "filePath": "resources.$group.$version.$plural.$system.$namespace.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
