{{- $image := required "backend.image is required" .Values.backend.image }}
{{- $ingressHost := required "ingress.host is required" .Values.ingress.host }}
{{- $ingressTlsSecret := required "ingress.tls.secret is required" .Values.ingress.tls.secret }}
{{- $secretName := required "backend.secretName is required" .Values.backend.secretName }}

apiVersion: acme.com/v1
kind: Workload
metadata:
  name: portal-backend
image: {{ $image }}
port: 3001
replicas: 2
expose:
  - path: /api
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
envFrom:
  - secretName: {{ $secretName }}
allowCluster:
  - apiGroup: "*"
    resource: "*"
    verbs: ["*"]
