{{- $image := required "backend.image is required" .Values.backend.image }}
{{- $ingressHost := required "ingress.host is required" .Values.ingress.host }}
{{- $ingressTlsSecret := required "ingress.tls.secret is required" .Values.ingress.tls.secret }}
{{- $secretName := required "backend.secretName is required" .Values.backend.secretName }}

apiVersion: acme.com/v1
kind: Workload
metadata:
  name: portal-backend
image: {{ $image }}
port: 3001
replicas: 2
expose:
  - path: /api(/|$)(.*)
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
envFrom:
  - secretName: {{ $secretName }}
{{- if .Values.redis.enabled }}
env:
  SLACK_API_TOKEN:
    fromSecret:
      secretName: {{ $secretName }}
      key: SLACK_API_TOKEN
  OPENAI_API_KEY:
    fromSecret:
      secretName: {{ $secretName }}
      key: OPENAI_API_KEY
  KBLOCKS_PUBSUB_HOST:
    value: "portal-redis.default.svc.cluster.local"
  KBLOCKS_PUBSUB_KEY:
    value: "pass1234"
{{- end }}
allowCluster:
  - apiGroup: "*"
    resource: "*"
    verbs: ["*"]
