{{- $image := default "wingcloudbot/kblocks-backend:latest" .Values.backend.image }}
{{- $secretName := required "backend.secretName is required" .Values.backend.secretName }}

apiVersion: acme.com/v1
kind: Workload
metadata:
  name: portal-backend
image: {{ $image }}
port: 3001
replicas: 2
{{ if .Values.ingress.enabled }}
{{- $ingressHost := required "ingress.host is required" .Values.ingress.host }}
{{- $ingressTlsSecret := .Values.ingress.tls.secret }}
expose:
  - path: /api(/|$)(.*)
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
{{- if $ingressTlsSecret }}
      secret: {{ $ingressTlsSecret }}
{{- end }}
{{- end }}

envFrom:
  - secretName: {{ $secretName }}
{{- if .Values.redis.enabled }}
env:
  SLACK_API_TOKEN:
    optional: true
    fromSecret:
      secretName: {{ $secretName }}
      key: SLACK_API_TOKEN
  OPENAI_API_KEY:
    optional: true
    fromSecret:
      secretName: {{ $secretName }}
      key: OPENAI_API_KEY
  KBLOCKS_PUBSUB_HOST:
    value: "portal-redis.default.svc.cluster.local"
  KBLOCKS_PUBSUB_KEY:
    value: "pass1234"
{{- end }}
allowCluster:
  - apiGroup: "*"
    resource: "*"
    verbs: ["*"]
