{{- $image := required "frontend.image is required" .Values.frontend.image }}
{{- $ingressHost := required "ingress.host is required" .Values.ingress.host }}
{{- $ingressTlsSecret := required "ingress.tls.secret is required" .Values.ingress.tls.secret }}

apiVersion: acme.com/v1
kind: Workload
metadata:
  name: portal-frontend
image: {{ $image }}
port: 80
replicas: 2
expose:
  - path: /assets(/|$)(.*)
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
  - path: /(.*)
    rewrite: /
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
allowCluster:
  - apiGroup: "*"
    resource: "*"
    verbs: ["*"]
