{{- $image := default "wingcloudbot/kblocks-frontend:latest" .Values.frontend.image }}

apiVersion: acme.com/v1
kind: Workload
metadata:
  name: portal-frontend
image: {{ $image }}
port: 80
replicas: 2
{{ if .Values.ingress.enabled }}
{{- $ingressHost := required "ingress.host is required" .Values.ingress.host }}
{{- $ingressTlsSecret := required "ingress.tls.secret is required" .Values.ingress.tls.secret }}
expose:
  - path: /assets(/|$)(.*)
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
  - path: /images(/|$)(.*)
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
  - path: /(.*)
    rewrite: /
    host: {{ $ingressHost }}
    tls:
      hosts:
        - {{ $ingressHost }}
      secret: {{ $ingressTlsSecret }}
{{- end }}
allowCluster:
  - apiGroup: "*"
    resource: "*"
    verbs: ["*"]
