{{- if eq true .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: portal-redis
spec:
  selector:
    app: portal-redis
  ports:
    - port: 18284
      targetPort: 18284
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-redis
spec:
  selector:
    matchLabels:
      app: portal-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: portal-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4.0-alpine
          args:
            - redis-server
            - --requirepass "pass1234"
            - --port 18284
          ports:
            - containerPort: 18284
{{- end }}
