{{- if .Values.secrets.portal.enabled }}
{{- $websiteOrigin := default "https://example.com" .Values.secrets.portal.websiteOrigin }}
{{- $supabaseUrl := default "https://example.supabase.co" .Values.secrets.portal.supabaseUrl }}
{{- $supabaseServiceKey := default "example-key" .Values.secrets.portal.supabaseServiceKey }}

apiVersion: v1
kind: Secret
metadata:
  name: kblocks-api-secrets
type: Opaque
stringData:
  PORT: "3001"
  KBLOCKS_NAMESPACE: kblocks
  WEBSITE_ORIGIN: {{ $websiteOrigin }}

  SUPABASE_URL: {{ $supabaseUrl }}
  SUPABASE_SERVICE_KEY: {{ $supabaseServiceKey }}

{{- if .Values.redis.enabled }}
  KBLOCKS_PUBSUB_HOST: "portal-redis.default.svc.cluster.local"
  KBLOCKS_PUBSUB_KEY: "pass1234"
{{- else }}
  KBLOCKS_PUBSUB_HOST: {{ .Values.secrets.portal.pubsubHost }}
  KBLOCKS_PUBSUB_KEY: {{ .Values.secrets.portal.pubsubKey }}
{{- end }}

{{- if .Values.secrets.portal.slackApiToken }}
  SLACK_API_TOKEN: {{ .Values.secrets.portal.slackApiToken }}
{{- end }}
{{- if .Values.secrets.portal.githubClientId }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.portal.githubClientId }}
{{- end }}
{{- if .Values.secrets.portal.githubClientSecret }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.portal.githubClientSecret }}
{{- end }}
{{- if .Values.secrets.portal.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.portal.openaiApiKey }}
{{- end }}

{{- end }}

{{- if .Values.secrets.kblocks.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kblocks
  namespace: kblocks
type: Opaque
stringData:
  KBLOCKS_ACCESS: read_write
  KBLOCKS_SYSTEM_ID: {{ .Values.localCluster.name | quote }}

{{- if .Values.redis.enabled }}
  KBLOCKS_PUBSUB_HOST: "portal-redis.default.svc.cluster.local"
  KBLOCKS_PUBSUB_PORT: "18284"
  KBLOCKS_PUBSUB_KEY: "pass1234"
{{- else }}
  KBLOCKS_PUBSUB_HOST: {{ .Values.secrets.kblocks.pubsubHost }}
  KBLOCKS_PUBSUB_PORT: {{ .Values.secrets.kblocks.pubsubPort }}
  KBLOCKS_PUBSUB_KEY: {{ .Values.secrets.kblocks.pubsubKey }}
{{- end }}

{{- end }}

{{- if .Values.secrets.gallery.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kblocks-gallery
  namespace: kblocks
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.gallery.awsAccessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.gallery.awsSecretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.secrets.gallery.awsRegion }}
  ORG_AWS_ACCESS_KEY_ID: {{ default .Values.secrets.gallery.awsAccessKeyId .Values.secrets.gallery.orgAwsAccessKeyId }}
  ORG_AWS_SECRET_ACCESS_KEY: {{ default .Values.secrets.gallery.awsSecretAccessKey .Values.secrets.gallery.orgAwsSecretAccessKey }}
  ORG_AWS_DEFAULT_REGION: {{ default .Values.secrets.gallery.awsRegion .Values.secrets.gallery.orgAwsRegion }}
  GITHUB_TOKEN: {{ .Values.secrets.gallery.githubToken }}
{{- end }}
