{{- if .Values.source }}
{{- if .Values.source.fromImage }}
{{- if .Values.source.fromImage.image }}
apiVersion: acme.com/v1
kind: NetworkedWorkload
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    foo: web
    hello: service
image: {{ .Values.source.fromImage.image }}
cpu:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
memory:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
{{- if .Values.environmentVariables }}
env:
  {{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}:
    {{- toYaml $value | nindent 4 }}
  {{- end }}
{{- end }}
scaling:  
  {{- if and .Values.scaling .Values.scaling.autoscaling }}
  autoscaling:
    minReplicas: {{ default 2 .Values.scaling.autoscaling.minReplicas }}
    maxReplicas: {{ default 5 .Values.scaling.autoscaling.maxReplicas }}
    targetCpuUtilization: {{ default 70 .Values.scaling.autoscaling.targetCpuUtilization }}
    targetMemoryUtilization: {{ default 70 .Values.scaling.autoscaling.targetMemoryUtilization }}
  {{- else }}
  replicas: {{ if and .Values.scaling (hasKey .Values.scaling "replicas") }}{{ .Values.scaling.replicas }}{{ else }}2{{ end }}
  {{- end }}
ingress:
  path: {{ .Values.route }}
  host: {{ .Values.host }}
  rewrite: {{ .Values.rewrite }}
  {{- if .Values.tls }}
  tls:
    secret: {{ .Values.tls.secret }}
    hosts: 
      {{- toYaml .Values.tls.hosts | nindent 6 }}
  {{- end }}
port: {{ default 3000 .Values.port }}
{{- end }}
{{- end }}
{{- end }}