{{- if .Values.source }}
{{- if .Values.source.fromImage }}
{{- if .Values.source.fromImage.image }}
apiVersion: acme.com/v1
kind: Worktmp
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    foo: web
    hello: service
image: {{ .Values.source.fromImage.image }}
cpu:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "cpu" | quote }}
memory:
  request: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
  limit: {{ get (get .Values.instanceTypes .Values.instanceType) "memory" | quote }}
scaling:  
  {{- if .Values.scaling.autoscaling }}
  autoscaling:
    minReplicas: {{ .Values.scaling.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.scaling.autoscaling.maxReplicas }}
    targetCpuUtilization: {{ .Values.scaling.autoscaling.targetCpuUtilization }}
    targetMemoryUtilization: {{ .Values.scaling.autoscaling.targetMemoryUtilization }}
  {{- else }}
  replicas: 2
  {{- end }}
region: {{ .Values.region }}
{{- if .Values.ingress }}
ingress:
  path: {{ .Values.ingress.path }}
  host: {{ .Values.ingress.host }}
  rewrite: {{ .Values.ingress.rewrite }}
  {{- if .Values.ingress.tls }}
  tls:
    secret: {{ .Values.ingress.tls.secret }}
    hosts: 
      {{- toYaml .Values.ingress.tls.hosts | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}