apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
spec:
  rules:
  - host: {{ .Values.argohost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-argocd-server
            port:
              number: 80
