apiVersion: kblocks.io/v1
kind: Project
metadata:
  name: private-service-demo
title: Private Service Demo
icon: Briefcase
description: >-
  A demo application that shows how Kblocks can be used to run a private service that is only accessible from the cluster
objects:
  - kblocks://acme.com/v1/privateservices/local/default/private-service-demo
---
apiVersion: acme.com/v1
kind: PrivateService
metadata:
  name: private-service-demo
instanceType: Small
port: 5678
source:
  fromImage:
    image: hashicorp/http-echo



