apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    costCenter: {{ .Values.costCenter }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        costCenter: {{ .Values.costCenter }}
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          env:
            - name: ECHO_TEXT
              value: {{ .Values.echoText }}
          ports:
            - containerPort: {{ .Values.port }}
