apiVersion: v1
kind: Namespace
metadata:
  name: cron
---
apiVersion: kblocks.io/v1
kind: Project
metadata:
  name: cron
  namespace: default
title: Cron Job Demo
icon: Clock
description: >-
  A demo application that shows how Kblocks can be used to run a Cron job
objects:
- kblocks://acme.com/v1/cronjobs/local/cron/my-cron-demo

---

apiVersion: acme.com/v1
kind: CronJob
metadata:
  name: my-cron-demo
  namespace: cron
instanceType: Small
region: us-east-1
schedule: '* * * * *'
source:
  fromImage:
    advanced:
      dockerCommand: ls
    image: busybox


