name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "20.17.0"
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
  GITHUB_CLIENT_ID: ${{ secrets.KBLOCKS_GITHUB_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.KBLOCKS_GITHUB_CLIENT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        run: supabase db start
        working-directory: apps/server

      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
        working-directory: apps/server
