name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: "20.17.0"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - run: npm install

      - run: source secrets/portal.env && echo $GITHUB_CLIENT_ID
      - run: echo $GITHUB_CLIENT_ID

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local development setup
        # run: source ../../secrets/portal.env && echo $GITHUB_CLIENT_ID && supabase db start
        run: npx dotenv -e ../../secrets/portal.env -- supabase db start
        working-directory: apps/server

      # - name: Verify generated types are checked in
      #   run: |
      #     source ../../secrets/portal.env && supabase gen types typescript --local > types.gen.ts
      #     if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
      #       echo "Detected uncommitted changes after build. See status below:"
      #       git diff
      #       exit 1
      #     fi
      #   working-directory: apps/server
