name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.17.0"

jobs:
  test:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: npm install # for some reason "npm ci" is not working

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin

      - name: Skaffold build
        id: build
        run: |
          skaffold build --platform=linux/arm64,linux/amd64 --file-output build.json
          echo "backend-tag=$(cat build.json | jq -r ".builds[0].tag")" >> $GITHUB_OUTPUT

      - name: Publish the backend
        run: |
          curl -X PATCH -H "content-type: application/json" "https://kblocks.io/api/resources/acme.com/v1/workloads/prod/default/portal-backend" -d '{"image":"${{ steps.build.outputs.backend-tag }}"}'

  deploy-gallery:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster:
          - kblocks-demo.quickube.sh
        block:
          - api-docs
          - autobuild
          - autobuild-static-site
          - aws-account
          - background-worker
          - bucket
          - cron-job
          - postgres
          - qkube
          - queue
          - redis
          - static-site
          - topic
          - workload
          - cloudfront
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install # for some reason "npm ci" is not working

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Create ~/.kube
        run: mkdir -p ~/.kube

      - name: Switch to the demo cluster
        run: npx qkube use ${{ matrix.cluster }}

      - name: Install ${{ matrix.block }}
        working-directory: gallery
        run: ./install-blocks.sh kblocks/${{ matrix.block }}
